[build]
  publish = "public"
  # Empty command or simple echo
  command = "echo Static site"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://bahai.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
